export default {
  COMMENT: 1,
  REACTION: 2,
  COSMO_COMMENT: 3,
  MATCH_WORD: 4,
  TRANSLATE: 5,
  RIGHT_TRANSLATION: 6,
  MISSING_WORD: 7,
  DELETE_WRONG: 8,
  IMAGE_COMMENT: 9,
  WORD_DESCRIPTION: 11
}
